name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: add googletest submodule
      run: |
        cd tests
        # if [-d "googletest" ]; then
        #   git clone --recursive https://github.com/google/googletest.git
        # else
        #   git submodule add https://github.com/google/googletest.git
        # fi
        git submodule init && git submodule update
        cd ..
    
    - name: build
      run: |
        mkdir build
        cd build
        g++ ../tests/test.cpp -o runAllTests
    
    - name: run tests
      run: |
        ./runAllTests
        cd ..
